using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Microsoft.CodeAnalysis.Testing.Verifiers;
using SourceKit.Generators.Builder.Annotations;
using SourceKit.Generators.Builder.Generators;
using SourceKit.Tests.Tools;
using Xunit;
using Verifier = Microsoft.CodeAnalysis.CSharp.Testing.CSharpSourceGeneratorVerifier<
    SourceKit.Generators.Builder.Generators.BuilderSourceGenerator,
    Microsoft.CodeAnalysis.Testing.Verifiers.XUnitVerifier>;

namespace SourceKit.Tests.Generators;

public class BuilderTests
{
    private const string GeneratedBuilderName =
        """
SourceKit.Generators.Builder/SourceKit.Generators.Builder.Generators.BuilderSourceGenerator/SomeQuery.SourceKit.Generation.Builder.cs
""";

    private const string GeneratedBuilder =
        """
// <auto-generated>
// This code was generated by a SourceKit.Builder code generator.
// https://github.com/itmo-is-dev/SourceKit
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;

namespace SourceKit.Sample.Generators
{
    public partial record SomeQuery
    {
        public static SomeQuery Build(Func<Builder, Builder> action)
        {
            return action(new Builder()).Build();
        }

        public sealed class Builder
        {
            private readonly List<System.Guid> _ids;
            private Int32 _count;
            public Builder()
            {
                _ids = new List<System.Guid>();
                _count = default;
            }

            public Builder WithId(Guid element)
            {
                _ids.Add(element);
                return this;
            }

            public Builder WithIds(IEnumerable<System.Guid> elements)
            {
                _ids.AddRange(elements);
                return this;
            }

            public Builder WithCount(Int32 value)
            {
                _count = value;
                return this;
            }

            public SomeQuery Build()
            {
                return new SomeQuery(_ids.Distinct().ToArray(), _count);
            }
        }
    }
}
""";

    [Fact]
    public async Task BuilderSourceGenerator_ShouldGenerateCorrectBuilderType()
    {
        var test = new CSharpSourceGeneratorTest<BuilderSourceGenerator, XUnitVerifier>
        {
            TestState =
            {
                Sources =
                {
                    await SourceFile.LoadAsync("SourceKit.Sample/Generators/SomeQuery.cs"),
                },
                GeneratedSources =
                {
                    new SourceFile(GeneratedBuilderName, GeneratedBuilder),
                },
                AdditionalReferences = { typeof(GenerateBuilderAttribute).Assembly },
                ReferenceAssemblies = ReferenceAssemblies.Net.Net60,
            },
        };

        await test.RunAsync();
    }
}