<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <NoWarn>$(NoWarn);RS1038</NoWarn>
    </PropertyGroup>

    <PropertyGroup>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <IsSourceKitPackage>true</IsSourceKitPackage>
    </PropertyGroup>

    <PropertyGroup>
        <Version>1.0.$(PatchVersion)$(VersionSuffix)</Version>
        <PackageReleaseNotes>Added GetRequiredService suppressor</PackageReleaseNotes>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\SourceKit.Analyzers.Annotations\SourceKit.Analyzers.Annotations.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false"/>
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="AnalyzerReleases.Shipped.md" Visible="false"/>
        <AdditionalFiles Include="AnalyzerReleases.Unshipped.md" Visible="false"/>
    </ItemGroup>

</Project>
