<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>

    <PropertyGroup>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <IsSourceKitPackage>true</IsSourceKitPackage>
    </PropertyGroup>

    <PropertyGroup>
        <Version>1.1.$(PatchVersion)$(VersionSuffix)</Version>
        <PackageReleaseNotes>
            Added GenerateBuilder attribute
        </PackageReleaseNotes>
    </PropertyGroup>

</Project>
