<Project>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup>
        <NoWarn>$(NoWarn);NU5128</NoWarn>
    </PropertyGroup>

    <PropertyGroup>
        <PatchVersion>0-local</PatchVersion>
        <VersionSuffix>-alpha</VersionSuffix>
    </PropertyGroup>

</Project>