<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>

    <Import Project="SourceKit.props"/>

    <ItemGroup>
        <None Update="Models\IncrementalValueProviderWrapper.tt" Generator="TextTemplatingFileGenerator" LastGenOutput="IncrementalValueProviderWrapper.cs"/>
        <Compile Update="Models\IncrementalValueProviderWrapper.cs" AutoGen="True" DesignTime="True" DependentUpon="IncrementalValueProviderWrapper.tt"/>

        <None Update="Extensions\ValueProviderExtensions.tt" Generator="TextTemplatingFileGenerator" LastGenOutput="ValueProviderExtensions.cs"/>
        <Compile Update="Extensions\ValueProviderExtensions.cs" AutoGen="True" DesignTime="True" DependentUpon="ValueProviderExtensions.tt"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.CodeAnalysis.Common" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all"/>
        <PackageReference Include="PolySharp" PrivateAssets="all"/>
    </ItemGroup>

</Project>