<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <NoWarn>$(NoWarn);RS1038;</NoWarn>
    </PropertyGroup>

    <PropertyGroup>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <IsSourceKitPackage>true</IsSourceKitPackage>
    </PropertyGroup>

    <PropertyGroup>
        <Version>1.3.$(PatchVersion)$(VersionSuffix)</Version>
        <PackageReleaseNotes>
            Added BuilderPropertyOptions
        </PackageReleaseNotes>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Humanizer.Core" GeneratePathProperty="true">
            <PrivateAssets Condition="'$(Configuration)' == 'Release'">all</PrivateAssets>
        </PackageReference>

        <PackageReference Include="Humanizer.Core.uk" GeneratePathProperty="true">
            <PrivateAssets Condition="'$(Configuration)' == 'Release'">all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\SourceKit.Generators.Builder.Annotations\SourceKit.Generators.Builder.Annotations.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false"/>
        <None Include="$(OutputPath)\$(AssemblyName).Annotations.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false"/>

        <None Include="$(PkgHumanizer_Core)\lib\netstandard2.0\*.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false"/>
        <None Include="$(PkgHumanizer_Core_uk)\lib\netstandard2.0\uk\*.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false"/>
    </ItemGroup>

</Project>
