<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <NoWarn>$(NoWarn);RS1038;</NoWarn>
    </PropertyGroup>

    <PropertyGroup>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <IsSourceKitPackage>true</IsSourceKitPackage>
    </PropertyGroup>

    <PropertyGroup>
        <Version>1.0.$(PatchVersion)$(VersionSuffix)</Version>
        <PackageReleaseNotes>
            Fixed alias generation for non-public types
        </PackageReleaseNotes>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentChaining" GeneratePathProperty="true">
            <PrivateAssets Condition="'$(Configuration)' == 'Release'">all</PrivateAssets>
        </PackageReference>

        <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" GeneratePathProperty="true">
            <PrivateAssets Condition="'$(Configuration)' == 'Release'">all</PrivateAssets>
        </PackageReference>

        <PackageReference Include="Humanizer.Core" GeneratePathProperty="true">
            <PrivateAssets Condition="'$(Configuration)' == 'Release'">all</PrivateAssets>
        </PackageReference>

        <PackageReference Include="Humanizer.Core.uk" GeneratePathProperty="true">
            <PrivateAssets Condition="'$(Configuration)' == 'Release'">all</PrivateAssets>
        </PackageReference>

        <PackageReference Include="Microsoft.Extensions.DependencyInjection" GeneratePathProperty="true">
            <PrivateAssets Condition="'$(Configuration)' == 'Release'">all</PrivateAssets>
        </PackageReference>

        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" GeneratePathProperty="true">
            <PrivateAssets Condition="'$(Configuration)' == 'Release'">all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\SourceKit.Generators.Grpc.Annotations\SourceKit.Generators.Grpc.Annotations.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false"/>

        <None Include="$(PkgFluentChaining)\lib\netstandard2.0\*.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false"/>
        <None Include="$(PkgMicrosoft_Bcl_AsyncInterfaces)\lib\netstandard2.0\*.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false"/>
        <None Include="$(PkgHumanizer_Core)\lib\netstandard2.0\*.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false"/>
        <None Include="$(PkgHumanizer_Core_uk)\lib\netstandard2.0\uk\*.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false"/>

        <None Include="$(PkgMicrosoft_Extensions_DependencyInjection)\lib\netstandard2.0\*.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false"/>
        <None Include="$(PkgMicrosoft_Extensions_DependencyInjection_Abstractions)\lib\netstandard2.0\*.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false"/>
    </ItemGroup>

</Project>
