using System.Collections.Immutable;
using FluentChaining;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Operations;
using Microsoft.Extensions.DependencyInjection;
using SourceKit.Extensions;
using SourceKit.Generators.Grpc.Builders.FileBuilders;
using SourceKit.Generators.Grpc.Builders.TypeBuilders;
using SourceKit.Generators.Grpc.Builders.UsingBuilders;
using SourceKit.Generators.Grpc.Commands;
using SourceKit.Generators.Grpc.Extensions;
using SourceKit.Generators.Grpc.Models;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace SourceKit.Generators.Grpc.Generators;

[Generator]
public sealed class ProtoMessageConstructorGenerator : IIncrementalGenerator
{
    private static readonly IChain<FileBuildingCommand, CompilationUnitSyntax> Chain;

    static ProtoMessageConstructorGenerator()
    {
        var collection = new ServiceCollection();

        collection.AddFluentChaining(x => x.ChainLifetime = ServiceLifetime.Singleton)
            .AddChain<FileBuildingCommand, CompilationUnitSyntax>(start =>
                start
                    .Then<UsingBuilder>()
                    .Then<TypeFileBuilder>()
                    .FinishWith((r, _) => r.CompilationUnit)
            )
            .AddChain<UsingBuildingCommand, UsingDirectiveSyntax>(start =>
                start
                    .Then<AutoGeneratedCommentBuilder>()
                    .Then<PragmaBuilder>()
                    .FinishWith((r, _) => r.Syntax)
            )
            .AddChain<TypeBuildingCommand, TypeDeclarationSyntax>(start =>
                start
                    .Then<ConstructorTypeBuilder>()
                    .FinishWith((r, _) => r.Syntax)
            );

        ServiceProvider? provider = collection.BuildServiceProvider();
        Chain = provider.GetRequiredService<IChain<FileBuildingCommand, CompilationUnitSyntax>>();
    }

    private static DiagnosticDescriptor FailureDescriptor { get; } = new(
        "SK2100",
        "Failed to generate proto message constructor",
        "Failed to generate proto message constructor. Error: '{0}', at '{1}'",
        "Usage",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<INamedTypeSymbol> assemblyTypes = context.CompilationProvider
            .SelectMany(static (compilation, ct) => compilation
                .EnumerateAllAvailableTypes(ct)
                .Where(type => type.ContainingAssembly.Equals(compilation.Assembly, SymbolEqualityComparer.Default)));

        IncrementalValueProvider<INamedTypeSymbol?> messageInterfaceSymbol = context.CompilationProvider
            .Select(static (compilation, _) => compilation
                .GetTypeByMetadataName(Constants.ProtobufMessageInterfaceFullyQualifiedName));

        IncrementalValuesProvider<ProtoMessage> protoMessages = assemblyTypes
            .Combine(messageInterfaceSymbol)
            .Where(static tuple => tuple.Right is not null)
            .Combine(context.CompilationProvider)
            .Select(static (tuple, _) => OnVisitNamedTypeSymbol(tuple.Left.Left, tuple.Left.Right!, tuple.Right))
            .Where(static message => message is not null)
            .Select(static (message, _) => message!);

        context.RegisterSourceOutput(
            protoMessages.Combine(context.CompilationProvider),
            static (context, tuple) =>
            {
                var (message, compilation) = tuple;

                try
                {
                    var command = new FileBuildingCommand(compilation, CompilationUnit(), message);
                    CompilationUnitSyntax compilationUnit = Chain.Process(command);

                    var fileName = $"{message.Type.GetFullyQualifiedName()}.{Constants.FilenameSuffix}";
                    string source = compilationUnit.NormalizeWhitespace(eol: "\n", elasticTrivia: true).ToFullString();

                    context.AddSource(fileName, source);
                }
                catch (Exception e)
                {
                    var diagnostic = Diagnostic.Create(
                        FailureDescriptor,
                        message.Type.GetSignatureLocations().First(),
                        e.Message,
                        e.StackTrace);

                    context.ReportDiagnostic(diagnostic);
                }
            });
    }

    private static ProtoMessage? OnVisitNamedTypeSymbol(
        INamedTypeSymbol symbol,
        INamedTypeSymbol messageInterfaceSymbol,
        Compilation compilation)
    {
        if (symbol.AllInterfaces.Contains(messageInterfaceSymbol, SymbolEqualityComparer.Default) is false)
            return null;

        ProtoProperty[] properties = ParseProperties(symbol, compilation).ToArray();

        INamedTypeSymbol? typesSymbol = symbol
            .GetMembers()
            .OfType<INamedTypeSymbol>()
            .SingleOrDefault(x => x.Name == "Types" && x.IsStatic);

        ProtoMessage[]? nestedMessages = typesSymbol?
            .GetMembers()
            .OfType<INamedTypeSymbol>()
            .Select(s => OnVisitNamedTypeSymbol(s, messageInterfaceSymbol, compilation))
            .WhereNotNull()
            .ToArray();

        return new ProtoMessage(symbol, properties, nestedMessages ?? []);
    }

    private static IEnumerable<ProtoProperty> ParseProperties(
        INamedTypeSymbol messageSymbol,
        Compilation compilation)
    {
        const string fieldNumberPostfix = "FieldNumber";

        INamedTypeSymbol? repeatedFieldType = compilation
            .GetTypeByMetadataName(Constants.ProtobufRepeatedFieldFullyQualifiedName);

        INamedTypeSymbol? mapFieldType = compilation
            .GetTypeByMetadataName(Constants.ProtobufMapFieldFullyQualifiedName);

        if (repeatedFieldType is null || mapFieldType is null)
            yield break;

        INamedTypeSymbol intSymbol = compilation.GetTypeSymbol<int>();

        ImmutableArray<ISymbol> members = messageSymbol.GetMembers();

        IEnumerable<IFieldSymbol> ordinalFields = members
            .OfType<IFieldSymbol>()
            .Where(x => x.IsConst)
            .Where(x => x.Type.Equals(intSymbol, SymbolEqualityComparer.Default))
            .Where(x => x.Name.EndsWith(fieldNumberPostfix));

        var oneOfCases = messageSymbol
            .GetTypeMembers()
            .Where(x => x.TypeKind is TypeKind.Enum)
            .SelectMany(x => x.GetMembers())
            .Select(x => x.Name)
            .ToImmutableHashSet();

        foreach (IFieldSymbol? ordinalField in ordinalFields)
        {
            if (ordinalField.ConstantValue is not int ordinal)
                continue;

            string propertyName = ordinalField.Name[..^fieldNumberPostfix.Length];

            IPropertySymbol? property = members
                .OfType<IPropertySymbol>()
                .SingleOrDefault(x => x.Name.Equals(propertyName));

            if (property is not { Type: INamedTypeSymbol propertyType })
                continue;

            bool isOneOf = oneOfCases.Contains(propertyName);
            bool? hasNullCheck = HasNullCheck(property, compilation);

            bool shouldAnnotateReferenceType = propertyType.IsReferenceType && (hasNullCheck is false || isOneOf);

            bool shouldAnnotateValueType =
                propertyType is { IsValueType: true, ConstructedFrom.SpecialType: not SpecialType.System_Nullable_T }
                && isOneOf;

            if (shouldAnnotateReferenceType || shouldAnnotateValueType)
            {
                propertyType = (INamedTypeSymbol)propertyType.WithNullableAnnotation(NullableAnnotation.Annotated);
            }

            if (propertyType.ConstructedFrom.Equals(repeatedFieldType, SymbolEqualityComparer.Default))
            {
                yield return new RepeatableProtoProperty(
                    propertyName,
                    ordinal,
                    (INamedTypeSymbol)propertyType.TypeArguments.Single());
            }
            else if (propertyType.ConstructedFrom.Equals(mapFieldType, SymbolEqualityComparer.Default))
            {
                yield return new MapProtoProperty(
                    propertyName,
                    ordinal,
                    (INamedTypeSymbol)propertyType.TypeArguments[0],
                    (INamedTypeSymbol)propertyType.TypeArguments[1]);
            }
            else
            {
                yield return isOneOf
                    ? new OneOfProtoProperty(propertyName, propertyType, ordinal)
                    : new ValueProtoProperty(propertyName, propertyType, ordinal);
            }
        }
    }

    private static bool? HasNullCheck(
        IPropertySymbol property,
        Compilation compilation)
    {
        if (property.Locations is not [var location])
            return null;

        var propertyNode = location.SourceTree?.GetRoot().FindNode(location.SourceSpan) as PropertyDeclarationSyntax;

        AccessorDeclarationSyntax? setterNode = propertyNode?.AccessorList?.Accessors
            .SingleOrDefault(x => x.Keyword.IsKind(SyntaxKind.SetKeyword));

        if (setterNode is not { Body: not null })
            return null;

        SemanticModel semanticModel = compilation.GetSemanticModel(setterNode.SyntaxTree);
        var operation = semanticModel.GetOperation(setterNode.Body) as IBlockOperation;

        return operation?.Descendants()
            .OfType<IInvocationOperation>()
            .Any(x => x.TargetMethod.Name.Equals("CheckNotNull"));
    }
}
