using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using SourceKit.Extensions;
using SourceKit.Generators.Grpc.Extensions;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace SourceKit.Generators.Grpc.Generators;

[Generator]
public sealed class ProtoMessageAliasGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<INamedTypeSymbol> allTypes = context.CompilationProvider
            .SelectMany(static (compilation, ct) => compilation.EnumerateAllAvailableTypes(ct));

        allTypes = allTypes
            .Where(type => type.ContainingNamespace.ToDisplayString().StartsWith("Google") is false);

        IncrementalValueProvider<INamedTypeSymbol?> messageInterfaceSymbol = context.CompilationProvider
            .Select(static (compilation, _) => compilation.GetTypeByMetadataName(
                Constants.ProtobufMessageInterfaceFullyQualifiedName));

        IncrementalValueProvider<INamedTypeSymbol?> enumAttributeSymbol = context.CompilationProvider
            .Select(static (compilation, _) => compilation.GetTypeByMetadataName(
                Constants.ProtobufOriginalNameAttributeFullyQualifiedName));

        IncrementalValuesProvider<INamedTypeSymbol> protoMessages = allTypes
            .Combine(messageInterfaceSymbol)
            .Where(static tuple => tuple.Right is not null)
            .Where(static tuple => tuple.Left.TypeKind is TypeKind.Class)
            .Where(static tuple => tuple.Left.AllInterfaces.Contains(tuple.Right!, SymbolEqualityComparer.Default))
            .Where(static tuple => tuple.Left.ContainingType is null)
            .Select(static (tuple, _) => tuple.Left);

        IncrementalValuesProvider<INamedTypeSymbol> protoEnums = allTypes
            .Combine(enumAttributeSymbol)
            .Where(static tuple => tuple.Left.TypeKind is TypeKind.Enum)
            .Where(static tuple => tuple.Left
                .GetMembers()
                .OfType<IFieldSymbol>()
                .All(member => member
                    .GetAttributes()
                    .Any(attr => attr.AttributeClass?.Equals(tuple.Right, SymbolEqualityComparer.Default) is true)))
            .Where(tuple => tuple.Left.ContainingType is null)
            .Select((tuple, _) => tuple.Left);

        IncrementalValueProvider<ImmutableArray<INamedTypeSymbol>> protoTypes = protoMessages
            .Collect()
            .Combine(protoEnums.Collect())
            .SelectMany((tuple, _) => tuple.Left.Concat(tuple.Right))
            .Collect();

        context.RegisterSourceOutput(
            protoTypes,
            static (context, protoTypes) =>
            {
                if (protoTypes is [])
                    return;

                UsingDirectiveSyntax[] directives = protoTypes
                    .GroupBy(x => x.Name, (k, values) => (k, values: values.ToArray()))
                    .Where(x => x.values.Length is 1)
                    .Select(x => x.values.Single())
                    .OrderBy(x => x.Name)
                    .Select(GenerateAlias)
                    .ToArray();

                if (directives is [])
                    return;

                CompilationUnitSyntax unit = CompilationUnit().AddUsings(directives).NormalizeWhitespace(eol: "\n");
                string text = unit.ToFullString();

                text = $"""
                // <auto-generated>
                //      This code was generated by a SourceKit.Generators.Grpc code generator.
                //      https://github.com/itmo-is-dev/SourceKit
                // </auto-generated>
                
                {text}
                """;

                context.AddSource("SourceKit.Generators.Builder.ProtoAlias.cs", text);
            });
    }

    private static UsingDirectiveSyntax GenerateAlias(INamedTypeSymbol symbol)
    {
        return UsingDirective(IdentifierName(symbol.GetFullyQualifiedName()))
            .WithGlobalKeyword(Token(SyntaxKind.GlobalKeyword))
            .WithAlias(NameEquals(IdentifierName($"Proto{symbol.Name}")));
    }
}
