using System.Text;
using Google.Protobuf;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Microsoft.CodeAnalysis.Testing.Verifiers;
using SourceKit.Generators.Builder.Annotations;
using SourceKit.Generators.Grpc.Generators;
using SourceKit.Tests.Tools;
using Xunit;

namespace SourceKit.Tests.Generators;

public class GrpcConstructorTests
{
    [Fact]
    public async Task ProtoMessageConstructorGenerator_ShouldGenerateCorrectConstructor()
    {
        var test = new CSharpSourceGeneratorTest<ProtoMessageConstructorGenerator, XUnitVerifier>
        {
            TestState =
            {
                Sources =
                {
                    new SourceFile("Model.cs", FileContent, Encoding.UTF8),
                },
                AdditionalReferences =
                {
                    typeof(GenerateBuilderAttribute).Assembly,
                    typeof(IMessage).Assembly,
                },
                ReferenceAssemblies = ReferenceAssemblies.Net.Net60,
            },
        };

        await test.RunAsync();
    }

    private const string FileContent = """
// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: model.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Playground {

  /// <summary>Holder for reflection information generated from model.proto</summary>
  public static partial class ModelReflection {

    #region Descriptor
    /// <summary>File descriptor for model.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ModelReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgttb2RlbC5wcm90bxoeZ29vZ2xlL3Byb3RvYnVmL3dyYXBwZXJzLnByb3Rv",
            "IqMDCgpQcm90b01vZGVsEjAKCnBhZ2VfdG9rZW4YASABKAsyHC5nb29nbGUu",
            "cHJvdG9idWYuU3RyaW5nVmFsdWUSDgoGdmFsdWVzGAIgAygJEhEKCXBhZ2Vf",
            "c2l6ZRgDIAEoBRISCgppbnRfdmFsdWVzGAQgAygFEhkKD2ludF9vbmVvZl92",
            "YWx1ZRgFIAEoBUgAEhwKEnN0cmluZ19vbmVvZl92YWx1ZRgGIAEoCUgAEh0K",
            "FW5vdF9udWxsX3N0cmluZ192YWx1ZRgHIAEoCRIzCg5udWxsX2ludF92YWx1",
            "ZRgIIAEoCzIbLmdvb2dsZS5wcm90b2J1Zi5JbnQzMlZhbHVlEjcKEW51bGxf",
            "c3RyaW5nX3ZhbHVlGAkgASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1Zh",
            "bHVlEiwKCW1hcF92YWx1ZRgKIAMoCzIZLlByb3RvTW9kZWwuTWFwVmFsdWVF",
            "bnRyeRovCg1NYXBWYWx1ZUVudHJ5EgsKA2tleRgBIAEoBRINCgV2YWx1ZRgC",
            "IAEoCToCOAFCBwoFdmFsdWVCDaoCClBsYXlncm91bmRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Playground.ProtoModel), global::Playground.ProtoModel.Parser, new[]{ "PageToken", "Values", "PageSize", "IntValues", "IntOneofValue", "StringOneofValue", "NotNullStringValue", "NullIntValue", "NullStringValue", "MapValue" }, new[]{ "Value" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ProtoModel : pb::IMessage<ProtoModel>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProtoModel> _parser = new pb::MessageParser<ProtoModel>(() => new ProtoModel());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProtoModel> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Playground.ModelReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtoModel() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtoModel(ProtoModel other) : this() {
      PageToken = other.PageToken;
      values_ = other.values_.Clone();
      pageSize_ = other.pageSize_;
      intValues_ = other.intValues_.Clone();
      notNullStringValue_ = other.notNullStringValue_;
      NullIntValue = other.NullIntValue;
      NullStringValue = other.NullStringValue;
      mapValue_ = other.mapValue_.Clone();
      switch (other.ValueCase) {
        case ValueOneofCase.IntOneofValue:
          IntOneofValue = other.IntOneofValue;
          break;
        case ValueOneofCase.StringOneofValue:
          StringOneofValue = other.StringOneofValue;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtoModel Clone() {
      return new ProtoModel(this);
    }

    /// <summary>Field number for the "page_token" field.</summary>
    public const int PageTokenFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _single_pageToken_codec = pb::FieldCodec.ForClassWrapper<string>(10);
    private string pageToken_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PageToken {
      get { return pageToken_; }
      set {
        pageToken_ = value;
      }
    }


    /// <summary>Field number for the "values" field.</summary>
    public const int ValuesFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_values_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> values_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Values {
      get { return values_; }
    }

    /// <summary>Field number for the "page_size" field.</summary>
    public const int PageSizeFieldNumber = 3;
    private int pageSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PageSize {
      get { return pageSize_; }
      set {
        pageSize_ = value;
      }
    }

    /// <summary>Field number for the "int_values" field.</summary>
    public const int IntValuesFieldNumber = 4;
    private static readonly pb::FieldCodec<int> _repeated_intValues_codec
        = pb::FieldCodec.ForInt32(34);
    private readonly pbc::RepeatedField<int> intValues_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> IntValues {
      get { return intValues_; }
    }

    /// <summary>Field number for the "int_oneof_value" field.</summary>
    public const int IntOneofValueFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int IntOneofValue {
      get { return HasIntOneofValue ? (int) value_ : 0; }
      set {
        value_ = value;
        valueCase_ = ValueOneofCase.IntOneofValue;
      }
    }
    /// <summary>Gets whether the "int_oneof_value" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasIntOneofValue {
      get { return valueCase_ == ValueOneofCase.IntOneofValue; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "int_oneof_value" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearIntOneofValue() {
      if (HasIntOneofValue) {
        ClearValue();
      }
    }

    /// <summary>Field number for the "string_oneof_value" field.</summary>
    public const int StringOneofValueFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StringOneofValue {
      get { return HasStringOneofValue ? (string) value_ : ""; }
      set {
        value_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        valueCase_ = ValueOneofCase.StringOneofValue;
      }
    }
    /// <summary>Gets whether the "string_oneof_value" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasStringOneofValue {
      get { return valueCase_ == ValueOneofCase.StringOneofValue; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "string_oneof_value" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearStringOneofValue() {
      if (HasStringOneofValue) {
        ClearValue();
      }
    }

    /// <summary>Field number for the "not_null_string_value" field.</summary>
    public const int NotNullStringValueFieldNumber = 7;
    private string notNullStringValue_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NotNullStringValue {
      get { return notNullStringValue_; }
      set {
        notNullStringValue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "null_int_value" field.</summary>
    public const int NullIntValueFieldNumber = 8;
    private static readonly pb::FieldCodec<int?> _single_nullIntValue_codec = pb::FieldCodec.ForStructWrapper<int>(66);
    private int? nullIntValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int? NullIntValue {
      get { return nullIntValue_; }
      set {
        nullIntValue_ = value;
      }
    }


    /// <summary>Field number for the "null_string_value" field.</summary>
    public const int NullStringValueFieldNumber = 9;
    private static readonly pb::FieldCodec<string> _single_nullStringValue_codec = pb::FieldCodec.ForClassWrapper<string>(74);
    private string nullStringValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NullStringValue {
      get { return nullStringValue_; }
      set {
        nullStringValue_ = value;
      }
    }


    /// <summary>Field number for the "map_value" field.</summary>
    public const int MapValueFieldNumber = 10;
    private static readonly pbc::MapField<int, string>.Codec _map_mapValue_codec
        = new pbc::MapField<int, string>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForString(18, ""), 82);
    private readonly pbc::MapField<int, string> mapValue_ = new pbc::MapField<int, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, string> MapValue {
      get { return mapValue_; }
    }

    private object value_;
    /// <summary>Enum of possible cases for the "value" oneof.</summary>
    public enum ValueOneofCase {
      None = 0,
      IntOneofValue = 5,
      StringOneofValue = 6,
    }
    private ValueOneofCase valueCase_ = ValueOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ValueOneofCase ValueCase {
      get { return valueCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearValue() {
      valueCase_ = ValueOneofCase.None;
      value_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProtoModel);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProtoModel other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PageToken != other.PageToken) return false;
      if(!values_.Equals(other.values_)) return false;
      if (PageSize != other.PageSize) return false;
      if(!intValues_.Equals(other.intValues_)) return false;
      if (IntOneofValue != other.IntOneofValue) return false;
      if (StringOneofValue != other.StringOneofValue) return false;
      if (NotNullStringValue != other.NotNullStringValue) return false;
      if (NullIntValue != other.NullIntValue) return false;
      if (NullStringValue != other.NullStringValue) return false;
      if (!MapValue.Equals(other.MapValue)) return false;
      if (ValueCase != other.ValueCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (pageToken_ != null) hash ^= PageToken.GetHashCode();
      hash ^= values_.GetHashCode();
      if (PageSize != 0) hash ^= PageSize.GetHashCode();
      hash ^= intValues_.GetHashCode();
      if (HasIntOneofValue) hash ^= IntOneofValue.GetHashCode();
      if (HasStringOneofValue) hash ^= StringOneofValue.GetHashCode();
      if (NotNullStringValue.Length != 0) hash ^= NotNullStringValue.GetHashCode();
      if (nullIntValue_ != null) hash ^= NullIntValue.GetHashCode();
      if (nullStringValue_ != null) hash ^= NullStringValue.GetHashCode();
      hash ^= MapValue.GetHashCode();
      hash ^= (int) valueCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (pageToken_ != null) {
        _single_pageToken_codec.WriteTagAndValue(output, PageToken);
      }
      values_.WriteTo(output, _repeated_values_codec);
      if (PageSize != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(PageSize);
      }
      intValues_.WriteTo(output, _repeated_intValues_codec);
      if (HasIntOneofValue) {
        output.WriteRawTag(40);
        output.WriteInt32(IntOneofValue);
      }
      if (HasStringOneofValue) {
        output.WriteRawTag(50);
        output.WriteString(StringOneofValue);
      }
      if (NotNullStringValue.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(NotNullStringValue);
      }
      if (nullIntValue_ != null) {
        _single_nullIntValue_codec.WriteTagAndValue(output, NullIntValue);
      }
      if (nullStringValue_ != null) {
        _single_nullStringValue_codec.WriteTagAndValue(output, NullStringValue);
      }
      mapValue_.WriteTo(output, _map_mapValue_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (pageToken_ != null) {
        _single_pageToken_codec.WriteTagAndValue(ref output, PageToken);
      }
      values_.WriteTo(ref output, _repeated_values_codec);
      if (PageSize != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(PageSize);
      }
      intValues_.WriteTo(ref output, _repeated_intValues_codec);
      if (HasIntOneofValue) {
        output.WriteRawTag(40);
        output.WriteInt32(IntOneofValue);
      }
      if (HasStringOneofValue) {
        output.WriteRawTag(50);
        output.WriteString(StringOneofValue);
      }
      if (NotNullStringValue.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(NotNullStringValue);
      }
      if (nullIntValue_ != null) {
        _single_nullIntValue_codec.WriteTagAndValue(ref output, NullIntValue);
      }
      if (nullStringValue_ != null) {
        _single_nullStringValue_codec.WriteTagAndValue(ref output, NullStringValue);
      }
      mapValue_.WriteTo(ref output, _map_mapValue_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (pageToken_ != null) {
        size += _single_pageToken_codec.CalculateSizeWithTag(PageToken);
      }
      size += values_.CalculateSize(_repeated_values_codec);
      if (PageSize != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PageSize);
      }
      size += intValues_.CalculateSize(_repeated_intValues_codec);
      if (HasIntOneofValue) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IntOneofValue);
      }
      if (HasStringOneofValue) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StringOneofValue);
      }
      if (NotNullStringValue.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NotNullStringValue);
      }
      if (nullIntValue_ != null) {
        size += _single_nullIntValue_codec.CalculateSizeWithTag(NullIntValue);
      }
      if (nullStringValue_ != null) {
        size += _single_nullStringValue_codec.CalculateSizeWithTag(NullStringValue);
      }
      size += mapValue_.CalculateSize(_map_mapValue_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProtoModel other) {
      if (other == null) {
        return;
      }
      if (other.pageToken_ != null) {
        if (pageToken_ == null || other.PageToken != "") {
          PageToken = other.PageToken;
        }
      }
      values_.Add(other.values_);
      if (other.PageSize != 0) {
        PageSize = other.PageSize;
      }
      intValues_.Add(other.intValues_);
      if (other.NotNullStringValue.Length != 0) {
        NotNullStringValue = other.NotNullStringValue;
      }
      if (other.nullIntValue_ != null) {
        if (nullIntValue_ == null || other.NullIntValue != 0) {
          NullIntValue = other.NullIntValue;
        }
      }
      if (other.nullStringValue_ != null) {
        if (nullStringValue_ == null || other.NullStringValue != "") {
          NullStringValue = other.NullStringValue;
        }
      }
      mapValue_.MergeFrom(other.mapValue_);
      switch (other.ValueCase) {
        case ValueOneofCase.IntOneofValue:
          IntOneofValue = other.IntOneofValue;
          break;
        case ValueOneofCase.StringOneofValue:
          StringOneofValue = other.StringOneofValue;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            string value = _single_pageToken_codec.Read(input);
            if (pageToken_ == null || value != "") {
              PageToken = value;
            }
            break;
          }
          case 18: {
            values_.AddEntriesFrom(input, _repeated_values_codec);
            break;
          }
          case 24: {
            PageSize = input.ReadInt32();
            break;
          }
          case 34:
          case 32: {
            intValues_.AddEntriesFrom(input, _repeated_intValues_codec);
            break;
          }
          case 40: {
            IntOneofValue = input.ReadInt32();
            break;
          }
          case 50: {
            StringOneofValue = input.ReadString();
            break;
          }
          case 58: {
            NotNullStringValue = input.ReadString();
            break;
          }
          case 66: {
            int? value = _single_nullIntValue_codec.Read(input);
            if (nullIntValue_ == null || value != 0) {
              NullIntValue = value;
            }
            break;
          }
          case 74: {
            string value = _single_nullStringValue_codec.Read(input);
            if (nullStringValue_ == null || value != "") {
              NullStringValue = value;
            }
            break;
          }
          case 82: {
            mapValue_.AddEntriesFrom(input, _map_mapValue_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            string value = _single_pageToken_codec.Read(ref input);
            if (pageToken_ == null || value != "") {
              PageToken = value;
            }
            break;
          }
          case 18: {
            values_.AddEntriesFrom(ref input, _repeated_values_codec);
            break;
          }
          case 24: {
            PageSize = input.ReadInt32();
            break;
          }
          case 34:
          case 32: {
            intValues_.AddEntriesFrom(ref input, _repeated_intValues_codec);
            break;
          }
          case 40: {
            IntOneofValue = input.ReadInt32();
            break;
          }
          case 50: {
            StringOneofValue = input.ReadString();
            break;
          }
          case 58: {
            NotNullStringValue = input.ReadString();
            break;
          }
          case 66: {
            int? value = _single_nullIntValue_codec.Read(ref input);
            if (nullIntValue_ == null || value != 0) {
              NullIntValue = value;
            }
            break;
          }
          case 74: {
            string value = _single_nullStringValue_codec.Read(ref input);
            if (nullStringValue_ == null || value != "") {
              NullStringValue = value;
            }
            break;
          }
          case 82: {
            mapValue_.AddEntriesFrom(ref input, _map_mapValue_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
""";
}