using System.Collections;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using SourceKit.Extensions;
using SourceKit.Generators.Builder.Annotations;
using SourceKit.Generators.Builder.Models;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace SourceKit.Generators.Builder.Generators;

[Generator]
public sealed class IncrementalBuilderGenerator : IIncrementalGenerator
{
    private static DiagnosticDescriptor FailureDescriptor { get; } = new(
        "SK2000",
        "Failed to generate builder",
        "Failed to generate builder. Error: {0}",
        "Usage",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValueProvider<IncrementalResult<INamedTypeSymbol>> attributeTypeProvider = context.CompilationProvider
            .Select(static (compilation, _) => compilation.GetTypeByMetadataName(Constants.GenerateBuilderAttributeFullyQualifiedName) is { } attributeType
                ? IncrementalResult.Success(attributeType)
                : IncrementalResult.Skip);

        IncrementalValuesProvider<BuilderDescriptor, Compilation> builderTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is TypeDeclarationSyntax,
                transform: static (context, _) => (TypeDeclarationSyntax)context.Node)
            .CombineAndUnwrap(attributeTypeProvider, context)
            .WithComparer(static (syntax, _) => syntax)
            .Where(static (typeSyntax, _) => typeSyntax.AttributeLists
                .SelectMany(list => list.Attributes)
                .Select(attribute => attribute.Name)
                .OfType<IdentifierNameSyntax>()
                .Any(name => name.Identifier.Text is Constants.GenerateBuilderAttributeName or Constants.GenerateBuilderAttributeShortName))
            .Combine(context.CompilationProvider)
            .WithComparer(static (syntax, _, _) => syntax)
            .Select((typeSyntax, attributeType, compilation) =>
            {
                SemanticModel semanticModel = compilation.GetSemanticModel(typeSyntax.SyntaxTree);
                INamedTypeSymbol? typeSymbol = semanticModel.GetDeclaredSymbol(typeSyntax);

                if (typeSymbol?.HasAttribute(attributeType!) is not true)
                    return IncrementalResult.Skip;

                return GenerateBuilderDescriptor(typeSymbol, compilation).Map(descriptor => (descriptor, compilation));
            })
            .WithTrackingName("MapBuilderProperties")
            .WithResultComparer((descriptor, _) => descriptor)
            .Unwrap(context);

        context.RegisterSourceOutput(
            builderTypes,
            (sourceContext, descriptor, compilation) =>
            {
                const string autoGeneratedComment = """
                // <auto-generated>
                // This code was generated by a SourceKit.Generators.Builder code generator.
                // https://github.com/itmo-is-dev/SourceKit
                // </auto-generated>
                """;

                try
                {
                    var builder = new BuilderSyntax(descriptor.ModelIdentifier);

                    foreach (IBuilderParameter property in descriptor.Properties)
                    {
                        property.Configure(builder, compilation);
                    }

                    TypeDeclarationSyntax modelSyntax = TypeDeclaration(descriptor.ModelKind, descriptor.ModelIdentifier)
                        .WithModifiers(TokenList(descriptor.ModelAccessModifiers.Append(Token(SyntaxKind.PartialKeyword))));

                    modelSyntax = builder.AddBuilder(modelSyntax);

                    NullableDirectiveTriviaSyntax nullableDirectiveTrivia = NullableDirectiveTrivia(Token(SyntaxKind.EnableKeyword), true);

                    MemberDeclarationSyntax member = descriptor.NamespaceIdentifier is null
                        ? modelSyntax
                        : NamespaceDeclaration(IdentifierName(descriptor.NamespaceIdentifier.Value)).AddMembers(modelSyntax);

                    member = member.WithLeadingTrivia(Trivia(nullableDirectiveTrivia));

                    CompilationUnitSyntax compilationUnit = CompilationUnit()
                        .AddUsings(
                            UsingDirective(IdentifierName(Constants.AnnotationsNamespace)),
                            UsingDirective(IdentifierName("System")),
                            UsingDirective(IdentifierName("System.Linq")))
                        .AddMembers(member);

                    compilationUnit = compilationUnit.WithLeadingTrivia(TriviaList(
                        Comment(autoGeneratedComment),
                        Trivia(PragmaWarningDirectiveTrivia(Token(SyntaxKind.DisableKeyword), true).AddErrorCodes(IdentifierName("CS1591")))));

                    var fileName = string.Format(Constants.GeneratedSourceNameTemplate, descriptor.ModelIdentifier);

                    sourceContext.AddSource(
                        fileName,
                        SourceText.From(compilationUnit.NormalizeWhitespace(eol: "\n").ToFullString(), Encoding.UTF8));
                }
                catch (Exception e)
                {
                    var diagnostic = Diagnostic.Create(
                        FailureDescriptor,
                        descriptor.ModelLocation,
                        e.Message);

                    sourceContext.ReportDiagnostic(diagnostic);
                }
            });
    }

    private IncrementalResult<BuilderDescriptor> GenerateBuilderDescriptor(
        INamedTypeSymbol modelSymbol,
        Compilation compilation)
    {
        ImmutableArray<IMethodSymbol> constructors = modelSymbol.Constructors;

        IMethodSymbol constructor;

        if (constructors is [var singleConstructor])
        {
            constructor = singleConstructor;
        }
        else
        {
            IMethodSymbol? primaryConstructor = constructors
                .SingleOrDefault(ctor => ctor.DeclaringSyntaxReferences.Any(syntax => syntax.GetSyntax() is TypeDeclarationSyntax));

            if (primaryConstructor is null)
            {
                var diagnostic = Diagnostic.Create(
                    FailureDescriptor,
                    modelSymbol.GetSignatureLocations().First(),
                    "Builder for types with multiple constructors only support primary constructors");

                return IncrementalResult.Failure(diagnostic);
            }

            constructor = primaryConstructor;
        }

        var properties = constructor.Parameters
            .Where(x => x.IsImplicitlyDeclared is false)
            .Select(x => MapToBuilderParameter(modelSymbol, x, compilation))
            .ToImmutableArray();

        var descriptor = new BuilderDescriptor(
            NamespaceIdentifier:
            modelSymbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : Identifier(modelSymbol.ContainingNamespace.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat.WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted))),
            ModelIdentifier: Identifier(modelSymbol.Name),
            ModelKind: modelSymbol.TypeKind switch
            {
                TypeKind.Class when modelSymbol.IsRecord => SyntaxKind.RecordDeclaration,
                TypeKind.Class => SyntaxKind.ClassDeclaration,
                TypeKind.Struct when modelSymbol.IsRecord => SyntaxKind.RecordStructDeclaration,
                TypeKind.Struct => SyntaxKind.StructDeclaration,
                _ => throw new ArgumentOutOfRangeException(),
            },
            ModelAccessModifiers: modelSymbol.DeclaredAccessibility.ToSyntaxTokenList(),
            ModelLocation: modelSymbol.GetSignatureLocations().First(),
            Properties: properties);

        return IncrementalResult.Success(descriptor);
    }

    private static IBuilderParameter MapToBuilderParameter(
        INamedTypeSymbol type,
        IParameterSymbol parameterSymbol,
        Compilation compilation)
    {
        ITypeSymbol propertyType = parameterSymbol.Type;
        INamedTypeSymbol enumerableType = compilation.GetTypeSymbol<IEnumerable>();

        INamedTypeSymbol constructorParameterAttribute = compilation.GetTypeSymbol<BuilderConstructorParameterAttribute>();
        INamedTypeSymbol builderPropertyAttribute = compilation.GetTypeSymbol<BuilderPropertyAttribute>();

        IParameterSymbol recordConstructorParameter = type.Constructors
            .SelectMany(x => x.Parameters)
            .Single(x => x.Name.Equals(parameterSymbol.Name));

        AttributeData? builderPropertyAttributeData = recordConstructorParameter
            .GetAttributes()
            .SingleOrDefault(data => data.IsAttribute(builderPropertyAttribute));

        BuilderPropertyOptions options = builderPropertyAttributeData is null
            ? default
            : (BuilderPropertyOptions)builderPropertyAttributeData.ConstructorArguments[0].Value!;

        if (parameterSymbol.GetAttributes().HasAttribute(constructorParameterAttribute)
            || recordConstructorParameter.GetAttributes().HasAttribute(constructorParameterAttribute))
        {
            options |= BuilderPropertyOptions.ConstructorParameter;
        }

        object? defaultValue = type.Constructors
            .SelectMany(x => x.Parameters)
            .Where(x => x.Name.Equals(parameterSymbol.Name))
            .Where(x => x.HasExplicitDefaultValue)
            .Select(x => x.ExplicitDefaultValue)
            .WhereNotNull()
            .SingleOrDefault();

        if (defaultValue is null 
            && propertyType.Equals(compilation.GetTypeSymbol<string>(), SymbolEqualityComparer.Default)
            && propertyType.NullableAnnotation is not NullableAnnotation.Annotated)
        {
            defaultValue = string.Empty;
        }

        var literalValue = new LiteralValue(defaultValue);

        if ((propertyType.IsAssignableTo(enumerableType) || propertyType is IArrayTypeSymbol)
            && propertyType.Equals(compilation.GetTypeSymbol<string>(), SymbolEqualityComparer.Default) is false)
        {
            ITypeSymbol elementType = propertyType.GetEnumerableTypeArgument(compilation);

            return new CollectionBuilderParameter(
                Identifier(parameterSymbol.Name),
                elementType.ToNameSyntax(includeGlobal: true),
                elementType,
                options);
        }

        return new ValueBuilderParameter(
            Identifier(parameterSymbol.Name),
            propertyType.ToNameSyntax(includeGlobal: true),
            propertyType.IsReferenceType,
            IsNullableReferenceType: propertyType.IsNullableReferenceType(),
            literalValue,
            options);
    }
}
