using System.Collections;
using System.Diagnostics;
using System.Text;
using FluentChaining;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Microsoft.Extensions.DependencyInjection;
using SourceKit.Extensions;
using SourceKit.Generators.Builder.Builders.BuilderTypeBuilders;
using SourceKit.Generators.Builder.Builders.FileBuilders;
using SourceKit.Generators.Builder.Builders.TypeBuilders;
using SourceKit.Generators.Builder.Builders.UsingBuilders;
using SourceKit.Generators.Builder.Commands;
using SourceKit.Generators.Builder.Models;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace SourceKit.Generators.Builder.Generators;

[Generator]
public sealed class IncrementalBuilderGenerator : IIncrementalGenerator
{
    private static DiagnosticDescriptor FailureDescriptor { get; } = new(
        "SK2000",
        "Failed to generate builder",
        "Failed to generate builder. Error: {0}",
        "Usage",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private readonly IChain<FileBuildingCommand, CompilationUnitSyntax> _chain;

    public IncrementalBuilderGenerator()
    {
        var collection = new ServiceCollection();

        collection.AddFluentChaining(x => x.ChainLifetime = ServiceLifetime.Singleton)
            .AddChain<FileBuildingCommand, CompilationUnitSyntax>
            (start => start
                .Then<UsingBuilder>()
                .Then<PropertyTypesUsingBuilder>()
                .Then<TypeBuilder>()
                .FinishWith((r, _) => r.CompilationUnit)
            )
            .AddChain<TypeBuildingCommand, TypeDeclarationSyntax>
            (start => start
                .Then<BuildMethodTypeBuilder>()
                .Then<BuilderTypeBuilder>()
                .FinishWith((r, _) => r.Syntax)
            )
            .AddChain<UsingBuildingCommand, UsingDirectiveSyntax>
            (start => start
                .Then<AutoGeneratedCommentBuilder>()
                .Then<PragmaBuilder>()
                .FinishWith((r, _) => r.Syntax)
            )
            .AddChain<BuilderTypeBuildingCommand, TypeDeclarationSyntax>
            (start => start
                .Then<FieldBuilderTypeBuilder>()
                .Then<ConstructorBuilderTypeBuilder>()
                .Then<CollectionMethodBuilderTypeBuilder>()
                .Then<ValueMethodBuilderTypeBuilder>()
                .Then<BuildMethodBuilderTypeBuilder>()
                .FinishWith((r, _) => r.BuilderSyntax)
            );

        ServiceProvider provider = collection.BuildServiceProvider();

        _chain = provider.GetRequiredService<IChain<FileBuildingCommand, CompilationUnitSyntax>>();
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValueProvider<IncrementalResult<INamedTypeSymbol>> attributeTypeProvider = context.CompilationProvider
            .Select(static (compilation, _) => compilation.GetTypeByMetadataName(Constants.GenerateBuilderAttributeFullyQualifiedName) is { } attributeType
                ? IncrementalResult.Success(attributeType)
                : IncrementalResult.Skip);

        IncrementalValuesProvider<(string, string)> builderTypes = context.SyntaxProvider
            .CreateSyntaxProvider(static (node, _) => node is TypeDeclarationSyntax, static (context, _) => (TypeDeclarationSyntax)context.Node)
            .CombineAndUnwrap(attributeTypeProvider, context)
            .WithComparer(static (syntax, _) => syntax)
            .Where(static (typeSyntax, _) => typeSyntax.AttributeLists
                .SelectMany(list => list.Attributes)
                .Select(attribute => attribute.Name)
                .OfType<IdentifierNameSyntax>()
                .Any(name => name.Identifier.Text is Constants.GenerateBuilderAttributeName or Constants.GenerateBuilderAttributeShortName))
            .Combine(context.CompilationProvider)
            .WithComparer(static (syntax, _, _) => syntax)
            .Select((typeSyntax, attributeType, compilation) =>
            {
                SemanticModel semanticModel = compilation.GetSemanticModel(typeSyntax.SyntaxTree);
                INamedTypeSymbol? typeSymbol = semanticModel.GetDeclaredSymbol(typeSyntax);

                if (typeSymbol?.HasAttribute(attributeType!) is not true)
                    return IncrementalResult.Skip;

                return GenerateForType(typeSymbol, compilation);
            })
            .Unwrap(context);

        context.RegisterSourceOutput(
            builderTypes,
            (sourceContext, symbol) =>
            {
                sourceContext.AddSource(
                    symbol.Item1,
                    SourceText.From(symbol.Item2, Encoding.Default));
            });
    }

    private IncrementalResult<(string, string)> GenerateForType(INamedTypeSymbol symbol, Compilation compilation)
    {
        try
        {
            BuilderProperty[] properties = symbol
                .GetMembers()
                .OfType<IPropertySymbol>()
                .Where(x => x.IsImplicitlyDeclared is false)
                .Where(x => x.IsAutoProperty())
                .Select(x => MapToBuilderProperty(symbol, x, compilation))
                .ToArray();

            var fileCommand = new FileBuildingCommand(
                compilation,
                CompilationUnit(),
                symbol,
                properties);

            CompilationUnitSyntax compilationUnit = _chain.Process(fileCommand);
            var fileName = $"{symbol.Name}.{Constants.FilenameSuffix}";

            return IncrementalResult.Success((fileName, compilationUnit.NormalizeWhitespace(eol: "\n").ToFullString()));
        }
        catch (Exception e)
        {
            var diagnostic = Diagnostic.Create(
                FailureDescriptor,
                symbol.GetSignatureLocations().First(),
                e.Message);

            return IncrementalResult.Failure(diagnostic);
        }
    }

    private static BuilderProperty MapToBuilderProperty(
        INamedTypeSymbol type,
        IPropertySymbol propertySymbol,
        Compilation compilation)
    {
        ITypeSymbol propertyType = propertySymbol.Type;
        INamedTypeSymbol enumerableType = compilation.GetTypeSymbol<IEnumerable>();

        INamedTypeSymbol constructorParameterAttribute = compilation
            .GetTypeSymbol(Constants.BuilderConstructorParameterAttributeFullyQualifiedName);

        IParameterSymbol recordConstructorParameter = type.Constructors
            .SelectMany(x => x.Parameters)
            .Single(x => x.Name.Equals(propertySymbol.Name));

        bool isBuilderConstructorParameter =
            propertySymbol.GetAttributes().HasAttribute(constructorParameterAttribute)
            || recordConstructorParameter.GetAttributes().HasAttribute(constructorParameterAttribute);

        object? defaultValue = type.Constructors
            .SelectMany(x => x.Parameters)
            .Where(x => x.Name.Equals(propertySymbol.Name))
            .Where(x => x.HasExplicitDefaultValue)
            .Select(x => x.ExplicitDefaultValue)
            .WhereNotNull()
            .SingleOrDefault();

        var literalValue = new LiteralValue(defaultValue);

        if (propertyType is not IArrayTypeSymbol && propertyType.IsAssignableTo(enumerableType) is false)
            return new BuilderProperty.Value(propertySymbol, propertyType, literalValue, isBuilderConstructorParameter);

        INamedTypeSymbol stringType = compilation.GetTypeSymbol<string>();

        if (propertyType.Equals(stringType, SymbolEqualityComparer.Default))
            return new BuilderProperty.Value(propertySymbol, propertyType, literalValue, isBuilderConstructorParameter);

        ITypeSymbol elementType = propertyType.GetEnumerableTypeArgument(compilation);

        if (propertyType is IArrayTypeSymbol)
        {
            return new BuilderProperty.Collection(
                propertySymbol,
                CollectionKind.Array,
                elementType,
                isBuilderConstructorParameter);
        }

        INamedTypeSymbol listType = compilation.GetTypeSymbol(typeof(List<>)).Construct(elementType);

        if (propertyType.Equals(listType, SymbolEqualityComparer.Default))
        {
            return new BuilderProperty.Collection(
                propertySymbol,
                CollectionKind.List,
                elementType,
                isBuilderConstructorParameter);
        }

        INamedTypeSymbol setType = compilation.GetTypeSymbol(typeof(HashSet<>)).Construct(elementType);

        if (propertyType.Equals(setType, SymbolEqualityComparer.Default))
        {
            return new BuilderProperty.Collection(
                propertySymbol,
                CollectionKind.HashSet,
                elementType,
                isBuilderConstructorParameter);
        }

        return new BuilderProperty.Collection(
            propertySymbol,
            CollectionKind.Array,
            elementType,
            isBuilderConstructorParameter);
    }
}
