using System.Text;
using Google.Protobuf;
using SourceKit.Generators.Grpc.Generators;
using SourceKit.Generators.Grpc.Tests.Tools;
using SourceKit.Tests.Common;
using SourceKit.Tests.Common.TestBases;
using Xunit;

namespace SourceKit.Generators.Grpc.Tests;

public class ProtoMessageConstructorGeneratorOldTests : GeneratorTestBase<ProtoMessageConstructorGenerator>
{
    [Fact]
    public async Task ProtoMessageConstructorGenerator_ShouldGenerateCorrectConstructor()
    {
        var protoSource = new SourceFile(
            Name: "model.proto",
            Content: """
            syntax = "proto3";
            option csharp_namespace = "SourceKit.Tests";
            
            message Model {
                int64 id = 1;
            }
            """);

        SourceFile[] compiledProtoSources = ProtocHelper.CompileFromSources(protoSource);

        var generatedSource = new SourceFile(
            Name: """
            SourceKit.Tests.Model.SourceKit.Generators.Grpc.g.cs
            """,
            Content: """
            // <auto-generated>
            //      This code was generated by a SourceKit.Generators.Grpc code generator.
            //      https://github.com/itmo-is-dev/SourceKit
            // </auto-generated>
            #pragma warning disable CS1591
            using System;
            using System.Collections.Generic;
            using System.Linq;
            
            #nullable enable
            namespace SourceKit.Tests
            {
                public partial class Model
                {
                    public Model(long id)
                    {
                        Id = id;
                    }
                }
            }
            """,
            Encoding: Encoding.UTF8);

        var addedSource = new SourceFile(
            Name: "Added.cs",
            Content: "public class A;",
            Encoding: Encoding.UTF8);

        await GeneratorTest
            .WithSources(compiledProtoSources)
            .WithGeneratedSource(generatedSource)
            .WithAdditionalReference(typeof(IMessage).Assembly)
            .WithDisabledDiagnostics("CS1701", "CS8019")
            .Build()
            .RunWithCacheVerificationAsync(addedSource);
    }
}
