using System.Text;
using Google.Protobuf;
using Microsoft.CodeAnalysis.Testing;
using SourceKit.Generators.Grpc.Generators;
using SourceKit.Tests.Common;
using SourceKit.Tests.Common.TestBases;
using Xunit;

namespace SourceKit.Generators.Grpc.Tests;

public class ProtoAliasGeneratorTests : GeneratorTestBase<ProtoMessageAliasGenerator>
{
    [Fact]
    public async Task ProtoMessageConstructorGenerator_ShouldGenerateCorrectConstructor()
    {
        var protoSource = new SourceFile(
            Name: "Model.cs",
            Content: """
            namespace My;
            
            public class Model : global::Google.Protobuf.IMessage<Model>;
            """,
            Encoding: Encoding.UTF8);

        var usageSource = new SourceFile(
            Name: "Client.cs",
            Content: """
            namespace My;
            
            public class Client
            {
                public void Do()
                {
                    var a = new ProtoModel();
                }
            }
            """,
            Encoding: Encoding.UTF8);
        
        var modifiedUsageSource = new SourceFile(
            Name: "Client.cs",
            Content: """
            namespace My;
            
            public class Client
            {
                public void Do()
                {
                    var a = new ProtoModel();
                    var b = new ProtoModel();
                }
            }
            """,
            Encoding: Encoding.UTF8);

        var aliasSource = new SourceFile(
            Name: """
            SourceKit.Generators.Grpc.ProtoAlias.DefinedMessages.g.cs
            """,
            Content: """
            // <auto-generated>
            //      This code was generated by a SourceKit.Generators.Grpc code generator.
            //      https://github.com/itmo-is-dev/SourceKit
            // </auto-generated>
            
            global using ProtoModel = global::My.Model;
            """,
            Encoding: Encoding.UTF8);
        
        var exportSource = new SourceFile(
            Name: """
            SourceKit.Generators.Grpc.ExportProtoAlias.DefinedMessages.g.cs
            """,
            Content: """
            // <auto-generated>
            //      This code was generated by a SourceKit.Generators.Grpc code generator.
            //      https://github.com/itmo-is-dev/SourceKit
            // </auto-generated>
            
            [assembly: global::SourceKit.Generators.Grpc.Annotations.ExportProtoAlias("ProtoModel", "global::My.Model")]
            """,
            Encoding: Encoding.UTF8);
        
        await GeneratorTest
            .WithSource(protoSource)
            .WithSource(usageSource)
            .WithGeneratedSource(exportSource)
            .WithGeneratedSource(aliasSource)
            .WithAdditionalReference(typeof(IMessage).Assembly)
            .WithCompilerDiagnostics(CompilerDiagnostics.None)
            .Build()
            .RunWithCacheVerificationAsync(modifiedUsageSource);
    }
}