<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>

    <PropertyGroup>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <IsSourceKitPackage>true</IsSourceKitPackage>
    </PropertyGroup>

    <PropertyGroup>
        <Version>1.0.$(PatchVersion)$(VersionSuffix)</Version>
        <PackageReleaseNotes>
            Added ExportProtoAliasAttribute
        </PackageReleaseNotes>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference
                Include="..\..\analyzers\SourceKit.Analyzers\SourceKit.Analyzers.csproj"
                PrivateAssets="contentfiles;build"/>
    </ItemGroup>

</Project>
