name: .NET

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/dotnet-build.yml'
      - '*.props'
      - '*.slnx'

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    permissions:
      packages: read

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 10.0.x

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: 'latest'

      - name: build sources
        run: |
          dotnet build SourceKit.slnx

      - name: Test
        run: dotnet test -c Release