name: "publish packages"

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - '.github/workflows/publish.yml'
      - '*.props'
      - '*.slnx'

  workflow_dispatch:

jobs:
  publish:
    name: build and publish
    runs-on: ubuntu-latest
    environment: nuget.org
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 10.0.x

      - name: remove tests
        run: |
          for file in "$(find ./tests -name '*.csproj')"
          do
            dotnet solution SourceKit.slnx remove "$file"
          done

      - name: remove samples
        run: |
          for file in "$(find ./samples -name '*.csproj')"
          do
            dotnet solution SourceKit.slnx remove "$file"
          done

      - name: build
        run: |
          mkdir -p ./bin/packages
          dotnet build SourceKit.slnx -c Release /p:PatchVersion=${{ github.run_number }} /p:IsWarmupBuild=true
          dotnet build SourceKit.slnx -c Release /p:PatchVersion=${{ github.run_number }}

      - name: publish to GitHub nuget repository
        run: |
          for file in bin/packages/*.nupkg
          do
            dotnet nuget push "${file#/}" --source "nuget.org" --api-key ${{ secrets.NUGET_API_KEY }}
          done