name: "publish packages"

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - '.github/workflows/publish.yml'
      - '*.props'
      - '*.targets'
      - '*.slnx'
      - 'scripts/**'

  workflow_dispatch:

jobs:
  publish:
    name: build and publish
    runs-on: ubuntu-latest
    environment: nuget.org
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 10.0.x

      - name: remove redundant projects
        run: |
          source ./scripts/scripts.sh
          
          remove_from_solution SourceKit.slnx ./samples
          remove_from_solution SourceKit.slnx ./tests

      - name: build
        run: |
          mkdir -p ./bin/packages
          dotnet build SourceKit.slnx -c Release /p:PatchVersion=${{ github.run_number }} /p:IsWarmupBuild=true
          dotnet build SourceKit.slnx -c Release /p:PatchVersion=${{ github.run_number }} /p:IsPackageBuild=true

      - name: publish to GitHub nuget repository
        run: |
          ls bin/packages
          
          for file in bin/packages/*.nupkg
          do
            dotnet nuget push "${file#/}" --source "nuget.org" --api-key ${{ secrets.NUGET_API_KEY }}
          done